create table account(
    id bigint generated by default as identity,
    email varchar(255) not null,
    password varchar(255) not null,
    primary key (id));

create table token(
    expired boolean not null,
    revoked boolean not null,
    account_id bigint,
    id bigint generated by default as identity,
    token varchar(255) unique,
    token_type varchar(255) check (token_type in ('BEARER')),
    primary key (id));

alter table if exists token add constraint FKftkstvcfb74ogw02bo5261kno foreign key (account_id) references account