server:
  port: 8080

spring:
  application:
    name: mail-registry
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: mail-registry
      properties:
        allow:
          auto:
            create:
              topics: true
    admin:
      auto-create: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/mail-registry
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  flyway:
    url: jdbc:postgresql://postgres:5432/mail-registry
    user: postgres
    password: postgres
  data:
    redis:
      host: redis
      port: 6379
#    hibernate:
#      ddl-auto: create-drop

jedis:
  pool:
    host: redis
    port: 6379
    maxTotal: 10
    maxIdle: 5
    maxWaitMillis: 10

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE

application:
  security:
    jwt:
      secret-key: superfuckingkafka123superfuckingkafka123superfuckingkafka123
      expiration: 86400000
      refresh-token:
        expiration: 86400000
